In [ ]:
import requests
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup

In [ ]:
movie_name=[]
year=[]
rating=[]
time=[]
genre=[]
description=[]

In [ ]:
pages=np.arange(1,10)

In [ ]:
for page in pages:
    page=requests.get("https://www.imdb.com/list/ls090245754/?st_dt=&mode=detail&page="+str(page)+"&sort=list_order,asc")
    soup=BeautifulSoup(page.content,'html.parser')  
    movies_data=soup.findAll('div',class_="lister-item mode-detail")
    for store in movies_data:
        name=store.h3.a.text
        movie_name.append(name)
        
        year_of_release=store.find('span',class_="lister-item-year text-muted unbold").text.replace('(','').replace(')','')
        year.append(year_of_release)
        
        runtime=store.find('span',class_="runtime").text
        time.append(runtime)
        
        rate=store.find('span',class_="ipl-rating-star__rating").text
        rating.append(rate)
        
        genres=store.find('span',class_="genre").text.strip()
        genre.append(genres)

In [ ]:
movie_df=pd.DataFrame({'Movie Name':movie_name,'Year':year,'Time':time,'Genre':genre,'Rating':rating})

In [27]:
movie_df

,Movie Name,Year,Time,Genre,Rating
0,Mononoke-hime,1997,134 min,"\nAnimation, Action, Adventure",8.3
1,3 Idiots,2009,170 min,"\nComedy, Drama",8.4
2,Dangal,2016,161 min,"\nAction, Biography, Drama",8.3
3,Koyaanisqatsi,1982,86 min,"\nDocumentary, Music",8.2
4,Full Metal Jacket,1987,116 min,"\nDrama, War",8.3
...,...,...,...,...,...
895,The Stranger,1946,95 min,"\nCrime, Drama, Film-Noir",7.3
896,Huang tu di,1984,86 min,"\nDrama, History, Music",7.1
897,Tarzan and His Mate,1934,104 min,"\nAction, Adventure, Romance",7.3
898,The Tales of Hoffmann,1951,133 min,"\nFantasy, Music, Musical",7.2
899,Knocked Up,2007,129 min,"\nComedy, Romance",6.9